# Introduction

The full introduction can be found in the 2021 GOA skate assessment [@Ormseth2021_skate_assessment]. What follows is an abbreviation of the 2021 introduction.

#### Description, scientific names, and general distribution
Skates (family *Rajidae*) are flat-bodied cartilaginous fishes related to sharks. At least 15 species of skates in four genera (*Raja*, *Beringraja*, *Bathyraja*, and *Amblyraja*) are commonly found in shallow inshore waters to very deep benthic habitats in Alaskan waters [@Eschmeyer1983_book; @Stevenson2007]. In the GOA, the most common skate species are  the Longnose skate (*Raja rhina*) and the Big skate (*Beringraja binoculata*). The range of the Big skate extends from the Bering Sea to southern Baja California in depths ranging from 2 to 800 m. The Longnose skate has a similar range, from the southeastern Bering Sea to Baja California in 9 to 1,069 m depths [@Love2005]. While these two species have wide depth ranges, they are generally found in shallow waters in the GOA. The remaining 13 species, all from the family *Bathyraja*, are treated as one group called "Other skates" in this assessment since they are markedly less common. Within this group, the three most common species are the Aleutian skate (*B. aleutica*), the Alaska skate (*B. parmifera*), and the Bering skate (*B. interrupta*). The Aleutian skate ranges throughout the north Pacific from northern Japan to northern California and has been found in waters 16 to 1,602 m deep. The Alaska skate is restricted to higher latitudes from the Sea of Okhotsk to the eastern Gulf of Alaska in depths from 17-392 m [@Stevenson2007]. The range of the Bering skate is difficult to determine at this time as it may actually be a complex of species, with each individual species occupying a different part of its general range from the western Bering Sea to southern California [@Love2005; @Stevenson2007]. 

The species within the skate assessment occupy different habitats and regions within the GOA groundfish Fishery Management Plan. This assessment distinguishs habitat primarily by depth for GOA skates. The highest biomass of skates is found in the shallowest continental shelf waters of less than 100-m depth and is normally dominated by Big skates, while Longnose skates are the most abundant species in the 101-200 m depth zone. Skates in the *Bathyraja* genus are dominant in the deeper waters extending from 200 to 1000 m or more in depth. These depth distributions are reflected in the spatial distribution of GOA skates. Big skates are located inshore and are most abundant in the central and western GOA. Longnose skates are located further offshore and are relatively less abundant in the western GOA. 

#### Life history and stock structure 
Skate life cycles are similar to sharks, with relatively low fecundity, slow growth to large body sizes, and dependence of population stability on high survival rates of a few well-developed offspring [@Moyle1996_book]. Sharks and skates in general have been classified as “equilibrium” life history strategists, with very low intrinsic rates of population increase implying that sustainable harvest is possible only at very low to moderate fishing mortality rates [@King2003]. Within this general equilibrium life history strategy, there can still be considerable variability between skate species in terms of life history parameters [@Walker1998]. 

While smaller-sized skate species have been observed to be somewhat more productive, large skate species with late maturation (11+ years) are most vulnerable to heavy fishing pressure [@Walker1998; @Frisk2001; @Frisk2002]. Several studies have explored the effects of fishing on a variety of skate species to determine which life-history traits and stages are the most important for management. Age and size at maturity and adult size/longevity appear to be more important predictors of resilience to fishing pressure than fecundity or egg survival. Skate species with the largest adult body sizes (and the empirically related large size/age at maturity, @Frisk2001) were least resilient to high fishing mortality rates. This is most often attributed to the long juvenile stage during which relatively large yet immature skates are exposed to fishing mortality. After an extensive review of population information for many elasmobranch species, @Frisk2001 recommended that precautionary management be implemented especially for the conservation of large species.







