# Analytical approach

All three GOA skates assessment groups are Tier 5 stocks that require an estimated biomass time series. A random effects (RE) model within the REMA model R package [@Sullivan2022] was used to produce biomass estimates suitable for harvest recommendations. The REMA model is a generalized random effects model for fitting biomass estimates with the option of including multiple survey strata. For each assessment group (Big, Longnose, and Other), a GOA-wide RE model was used to determine the recommended OFL and GOA-wide ABC. For Big and Longnose skates, a regional-specific (Western, Central and Eastern) REMA model was run to determine the proportion of the GOA-wide biomass within each region. The biomass in each region was determined by multiplying the proportion, determined by the region specific REMA model, by the GOA-wide biomass, determined by GOA-wide RE model. The confidence intervals for the region specific biomass was determined by assuming the standard error of the log of the proportion by region multiplied by the GOA-wide biomass was equivalent to the standard error of the log of the region specific biomass determined by the region specific REMA model.


## Parameter Estimates

*Natural Mortality (M)*

An *M* value of 0.1 was used for all three GOA skate assessment groups.

