# Results

For all three assessment groups, the GOA-wide projected biomass for `r year +1` was lower than the projected biomass for `r year` from last years assessment. For Big and Longnose skates, the decrease was small (`r format(bg_bio[2], big.mark=",") ` t to `r format(bg_bio[3], big.mark=",") ` t, a `r round(bg_bio_ch,2)`% decline for Big skate and `r format(ln_bio[2], big.mark=",") ` t to `r format(ln_bio[3], big.mark=",") ` t, a `r round(ln_bio_ch,2)`% decline for Longnose skate). The decline in Other skates was the largest (`r format(ot_bio[2], big.mark=",") ` t to `r format(ot_bio[3], big.mark=",") ` t, a `r round(ot_bio_ch,2)`% decline for Other skates). Other skates had a large decline from 2013 to 2019 and have remained low ever since. It is difficult to say whether Other skates biomass is still declining however the `r year` estimate (`r format(round(ot_cur_bio), big.mark=",") ` t) is the lowest since 1995.

The region specific biomass estimates for Big and Longnose skates can be used to determine whether changes to the population biomass are GOA-wide or region specific. For Big skate, the WGOA and CGOA projected biomass for `r year +1` was higher than the their projected biomass for `r year` from last years assessment (`r format(bg_bio_pred[1,2], big.mark=",") ` t to `r format(bg_bio_pred[1,3], big.mark=",") ` t, a `r round(bg_w_ch,2)`% increase for WGOA and `r format(bg_bio_pred[2,2], big.mark=",") ` t to `r format(bg_bio_pred[2,3], big.mark=",") ` t, a `r round(bg_c_ch,2)`% increase for CGOA). The only area that had a decrease was EGOA (`r format(bg_bio_pred[3,2], big.mark=",") ` t to `r format(bg_bio_pred[3,3], big.mark=",") ` t, a `r round(bg_e_ch,2)`% decline). EGOA has the smallest estimated biomass out of all three areas and is at its lowest estimated value since 1990. The exploitation rate (catch/biomass) for EGOA has been relatively high for the past four years when compared to the entire exploitation rate time series except for 2006 (Figure `r params$chapter`-\@ref(fig:fig-area-exploit)). However, the total catch of Big skate in EGOA has remained below the TAC since at least 2005 (Figure `r params$chapter`-\@ref(fig:fig-area-cat-ofl)). 

As for the Longnose skate region specific biomass estimates, they all declined except for EGOA (`r format(ln_bio_pred[1,2], big.mark=",") ` t to `r format(ln_bio_pred[1,3], big.mark=",") ` t, a `r round(ln_w_ch,2)`% decrease for WGOA, `r format(ln_bio_pred[2,2], big.mark=",") ` t to `r format(ln_bio_pred[2,3], big.mark=",") ` t, a `r round(ln_c_ch,2)`% decrease for CGOA and `r format(ln_bio_pred[3,2], big.mark=",") ` t to `r format(ln_bio_pred[3,3], big.mark=",") ` t, a `r round(ln_e_ch,2)`% increase for EGOA). The largest decline occurred in WGOA which had the smallest estimated biomass. It is difficult to determine if this decrease is a sign of a declining population in WGOA or if this is just variability in the survey biomass estimates, which has wide confidence intervals, or natural annual variability (Figure `r params$chapter`-\@ref(fig:fig-ln-index)). It is also important to point out that, as of `r cat_dat_date`, the catch in EGOA is above the ABC (Figure `r params$chapter`-\@ref(fig:fig-area-cat-ofl)). This is the first time this has happened since at least 2005. However, the catch in EGOA has been close to the ABC for the past two years. Also, for the past two years the exploitation rate in EGOA has been high when compared to the entire exploitation rate time series. The highest exploitation rate occurred in `r year` (Figure `r params$chapter`-\@ref(fig:fig-area-exploit)).  


## Exploitation Rates
The GOA-wide exploitation rates have alot of inter-annual variability (Figure `r params$chapter`-\@ref(fig:fig-tot-exploit)). Other skates tend to have the highest exploitation rates with considerable inter-annual variability (values ranging from 0.094 - 0.035 since 2016). Big and Longnose skates have had low exploitation rates with values below 0.04 since 2017. The area specific exploitation rates for Big skate show a declining trend for CGOA and WGOA while EGOA has been increasing since 2019. In `r year`, all three areas have exploitation rates below 0.03, as of `r cat_dat_date` (Figure `r params$chapter`-\@ref(fig:fig-area-exploit)). As for Longnose skate area specific exploitation rates, CGOA has been declining since 2013 with a `r year` value of 0.015, EGOA has been increasing since 2018 with a `r year` value of 0.085 and WGOA has alot of interannual variability with a `r year` value of 0.042. All the `r year` Longnose skate area specific exploitation rate values are as of `r cat_dat_date` (Figure `r params$chapter`-\@ref(fig:fig-area-exploit)). 

